### PR TITLE
Plugin update

### LINKED ISSUE #38: Logging is misleading
The url of the record is only the first url it hit, and any more that hit the same host will increase the count.

This is a bit misleading, e.g.

first hit: `mysite.com/test`
other hits: `mysite.com/test2`, `mysite.com/test3`

this would end up with a record that shows `mysite.com/test` with the count of 3, but the stacktrace is the latest

This also hides what is actually calling a url, as there might be multiple places in a single plugin calling one url where they will fight themselves in the db to be seen.

To do:
- [ ] Store a sha hash based off the code path + url.
- [ ] Unique index in the db for this
- [ ] Use as reference instead of current host

### LINKED ISSUE #39: DB performance issues
- There is an index on the count, which seems unnecessary
- The DB update seems to update a lot of stuff that seems unnecessary

### PR DESCRIPTION
**Pull request by matthewhilton**
Closes #38 Closes #39 

**Changes**
- Adds `reference` string column, a sha of the codepath + full url (without query param). This is to properly log situations that would have gotten mixed up before (when you only compare the host url), such as:
     1. when two codepaths call the same url
     2. when one codepath calls multiple urls.
- The codepath column is quite big so using a SHA instead of full text search to speed up db, since this function needs to be as lightweight as possible as some pages generate lots of curl calls per request.
 - Small refactor of class to be better compartmentalised
 - Added some basic unit tests (there were none before :see_no_evil: )
 - Removed other indexes, they were unnecessary (like the one on `count`)
 - Add ci + general phpcs cleanup
 - Tweaked branches, added `MOODLE_401_STABLE` branch to align with current branch naming schemes

**Testing**
- Unit tests added (passing in CI)
- Manual testing - tested logging & it works as expected

**To do:**
- [x] CI fixup
- [x] New base branch, MOODLE_401_STABLE ?
- [x] Branch protections

### CODE REVIEW

File: classes/curlmanager_security_helper.php [hunk 1]
```diff
@@ -22,150 +29,134 @@
...
+
+            // Log the result.
+            $this->log_curl_http_requests($url, $blockedbymoodle, $blockedbyus);
 
-        // Log the http request.
-        return $this->log_curl_http_requests($urlstring);
+            return $blockedbymoodle || $blockedbyus;
+        } catch (Throwable $e) {
+            // Block if there is any error.
+            return true;
```
Comment (Peterburnett) [inline classes/curlmanager_security_helper.php]: I think failing open here is the safer call. In conjunction with password validator, this may prevent logins at all

File: classes/curlmanager_security_helper.php [hunk 2]
```diff
@@ -22,150 +29,134 @@
...
-        return false;
+        // Get path (without any query params).
+        $urlstring = self::sanitise_url($url);
+        $reference = self::get_reference($url, $formattedbacktrace);
+
+        // Upsert log using reference to de-dup.
+        $record = $DB->get_record('tool_curlmanager', ['reference' => $reference], 'id,count', IGNORE_MISSING);
+
+        if (!empty($record)) {
+            $DB->update_record('tool_curlmanager', [
```
Comment (Peterburnett) [inline classes/curlmanager_security_helper.php:116]: So I was a little suspect of this previously overwriting data that wasnt required. I think we should remove urlallowed and urlblocked from the upserts, and instead add it to the reference hash so that if it changes, it will be logged to a different line, but that way we don't need to overwrite it on every curl invocation

thoughts?

Comment (matthewhilton) [reply classes/curlmanager_security_helper.php:116]: agreed - i'll add it in

File: classes/curlmanager_security_helper.php (hunk 1 above)
Comment (matthewhilton) [reply classes/curlmanager_security_helper.php]: I think it would be up to the business / site owner, so im thinking putting it behind a config

File: classes/curlmanager_security_helper.php [hunk 3]
```diff
@@ -22,150 +29,134 @@
...
-     * @return array
-     * @throws \dml_exception
+     * @param string $host
+     * @return bool true if is whitelisted, else false
      */
-    private function host_is_allowed($host) {
-
-        $returnvalue = [];
-
+    private function host_is_whitelisted($host): bool {
```
Comment (rhell4) [inline classes/curlmanager_security_helper.php]: Is there a reason for changing the function name? I think as a standard we are moving away from the whitelist/blacklist naming conventions and moving towards allowlist/blocklist.

Comment (matthewhilton) [reply classes/curlmanager_security_helper.php]: No reason just habit - have updated all the references to be allowlist/blocklist

**Comment by rhell4** [comment]
Looks good to me, merging.
